### ISSUE TITLE
x_tm1iables

### ISSUE THREAD

**Issue by cancan101** [tdozat/Optimization#1]
What is `x_tm1iables`? It is used but never defined: https://github.com/tdozat/Optimization/search?utf8=%E2%9C%93&q=x_tm1iables

**Comment by tdozat** [comment]
Whoops, I must've done a less-than-careful "replace all" ("var" => "x_tm1"). It should be fixed now!

**Comment by cancan101** [comment]
@tdozat I think you want to update `optimizer.py` as well
